site_name: CBSP Labs
site_url: https://polaris.fri.uni-lj.si/cbsp/
docs_dir: docs

theme:
  name: material

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: si
          default: true
          name: Slovenščina
        - locale: en
          name: English
