site_name: CBSP Labs
site_url: https://polaris.fri.uni-lj.si/cbsp/
docs_dir: .   # use current folder as docs root (en/ and si/ live here)

theme:
  name: material

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: si
	  default: true
          name: Slovenščina
        - locale: en
          name: English
