site_name: CPNS Labs
site_url: https://polaris.fri.uni-lj.si/cpns/
docs_dir: docs

theme:
  name: material

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: si
          default: true
          name: Slovenščina
          link: /cpns/ 
        - locale: en
          name: English
          link: /cpns/en/

nav:
  - Home: index.md
  - Lab 1: ./lab1/lab1.md
  - Lab 2: ./lab2/lab2.md
  - Lab 3: ./lab3/lab3.md
  - Lab 4: ./lab4/lab4.md
  - Lab 5: ./lab5/lab5.md
  - Lab 6: ./lab6/lab6.md
  - Lab 7: ./lab7/lab7.md
  - Lab 8: ./lab8/lab8.md
  - Lab 9: ./lab9/lab9.md
  - Lab 10: ./lab10/lab10.md
  - Lab 11: ./lab11/lab11.md
  - Lab 12: ./lab12/lab12.md
  - Lab 13: ./lab13/lab13.md
